//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurcach
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zatrat
    {
        public int id { get; set; }
        public string vid_zatrat { get; set; }
        public decimal Stoim { get; set; }
        public System.DateTime Data { get; set; }
    }
}
